version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: teamcity_db
    restart: always
    ports:
      - ${TEAMCITY_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_PASSWORD}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASSWORD}
      - MYSQL_DATABASE=teamcity
    volumes:
      - ./data/mysql-db:/var/lib/mysql

  teamcity:
    image: jetbrains/teamcity-server:2023.11.3
    container_name: teamcity
    restart: always
    ports:
      - ${TEAMCITY_PORT}:8111
    volumes:
      - ./data/team-city/server/data:/data/teamcity_server/datadir
      - ./data/team-city/server/logs:/opt/teamcity/logs
    user: root
    depends_on:
      - db

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:2023.11.3-linux-sudo
    container_name: teamcity_agent_1
    restart: always
    privileged: true
    volumes:
      - ./data/team-city/agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  teamcity-agent-2:
    image: jetbrains/teamcity-agent:2023.11.3-linux-sudo
    container_name: teamcity_agent_2
    restart: always
    privileged: true
    volumes:
      - ./data/team-city/agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
